aws_lambda/aws_lambda.py
aws_lambda/project_template/config.yaml

If role isn't specified the lambda function is created with the default "lambda_basic_execution" role.
Motivation: 
I need to configure my lambda function with a custom role, unfortunately adding
```
role: lambda_kinesis_execution
```
in the config.yaml wasn't yet respected - where `lambda_kinesis_execution` is the custom role I have created beforehand.
This PR should add this desired functionality.

Add support for custom roles in config

---

aws_lambda/aws_lambda.py
scripts/lambda

If you want to deploy your lambda function and need a dependency which
is not available on PyPi, but only to your local machine (private package, ...)
you can now add this to the dist archive as well.
For both, the `build` and `deploy` option, an optional argument `--local-package`
can be provided with the path to the package you want to install via pip.
Your package needs to have a `setup.py` file.
Example:
$ lambda build --local-package .

Add option to install a local package to be deployed as well

---

aws_lambda/__init__.py
aws_lambda/aws_lambda.py
requirements.txt
scripts/lambda

This PR adds another CLI option to delete old versions of a deployed lambda function.
The subcommand accepts an command line option or will prompt the user for a valid input.
The command deletes all old versions except for the last `n` versions.
Furthermore `$Latest` and any aliased version will be kept.

Delete old versions of deployed function

---

aws_lambda/aws_lambda.py

This approach will work with both normal IAM account credentials and assumed roles.

Use STS to fetch the account ID instead of IAM

---

requirements.txt

Update to the latest supported versions of Boto 3 (1.4.1) and Botocore (1.4.61).
Ref: http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

Update boto3 and botocore to Latest Versions

---

scripts/lambda

`lambda init` now takes an optional folder name.
eg: `lambda init example_lambda`
- Creates the folder if it doesn't exist
- Sample files are created in the folder if it exits
- If the name provided is a file, throws an exception.

lambda init accepts optional folder name

---

aws_lambda/aws_lambda.py

We use this package to deploy lambda functions for an in-house project. As of today we got the following error,
```
Starting new HTTPS connection (1): lambda.us-west-2.amazonaws.com
Updating your Lambda function
Starting new HTTPS connection (1): sts.amazonaws.com
Starting new HTTPS connection (1): lambda.us-west-2.amazonaws.com
Traceback (most recent call last):
File "/home/travis/build/OpenTrons/foo-bar/lambdas/data-upload/venv/bin/lambda", line 53, in <module>
cli()
File "/home/travis/build/OpenTrons/foo-bar/lambdas/data-upload/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/home/travis/build/OpenTrons/foo-bar/lambdas/data-upload/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File …
```

add keyword arg for VpcConfig on lambda function update

---

aws_lambda/aws_lambda.py
requirements.txt
scripts/lambda

Install only required packages if option is set
The current solution installs all packages found by pip freeze to the
distribution folder and deploys this to AWS Lambda.
This includes some unnecessary packages to run the code, e.g. testing modules
which increase the distribution size.
The option to install only required packages helps reducing the build size.
For now, the file must be named `requirements.txt` and be in the same
directory of the project which shall be uploaded.
A new optional flag is added to the CLI and the package itself (`python-lambda`) is removed from the 
requirements file of this project. It shouldn't install itself.

Requirements only

---

.gitignore
README.rst
aws_lambda/aws_lambda.py
aws_lambda/helpers.py
aws_lambda/project_templates/config.yaml

**Python 3.6 Support (Local Environment)**
Building and deploying lambda functions wasn't working with python3.6.  The issue was that the default encoding for files is UTF-8 and we're opening up the zip files to create or update a function.  We were getting the following error in the read() method in the helper module.
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".../python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 12: invalid continuation byte
```
I added an optional parameter to the helper.py read() call that defines whether the file is binary or not.  This allows us to read the zip file during deployment.
To assist users …

Support for Python 3.6 & removing requirement to store secrets/environment values in the config file

---

aws_lambda/aws_lambda.py

Push environment variables from the config file into the actual environment when calling invoke.

---

README.rst
aws_lambda/__init__.py
aws_lambda/aws_lambda.py
aws_lambda/project_templates/config.yaml
scripts/lambda

Please feel free to close if this is deemed unnecessary.  
This is a great toolkit, however, we've been using other tools to deploy/manage lambda configurations.  I found that I simply need this toolkit to upload the zipped file to S3 instead of actually deploying the lambda itself.  I tried to stay within patterns already established in this repo so this PR may look a little copy/paste-y.  Provided that the user adds the destination S3 bucket (and the optional key) to `config.yaml`, he or she can just execute `lambda upload` to build the zip file and send it off to S3.
Any feedback would be much appreciated.

Adding function to upload zip file to S3

---

aws_lambda/aws_lambda.py

ARNs in GovCloud start with `arn:aws-us-gov:`, so this PR passes the region to `get_role_name()` so a proper ARN can be created.

Fix for GovCloud support

---

aws_lambda/aws_lambda.py
aws_lambda/project_templates/config.yaml

This is related to issue #64 not working as expected.  Added the capability to copy source directories into the zip package in the build process.  To control which folders are copied (as there may be additional folders that shouldn't be deployed within the project structure), there is a new build configuration section in the config.yaml file that includes a new property "source_directories".  
_Note: This makes it much easier to build a lambda function that talks to Redshift/Postgres databases using the precompiled psycopg2._

Including Source folders in the deployment zip package (build process)

---

aws_lambda/aws_lambda.py

We want to publish the function after updating the config, so the newly
created versions pick up an eventually updated function description.

Make function publishing the last step

---

aws_lambda/aws_lambda.py

This should fix issue https://github.com/nficano/python-lambda/issues/71 , please review

fix exception on invoke when no env vars found in config

---

setup.py

Currently, the `futures` package is installed via `requirements.txt` any time python-lambda is installed.  The `futures` package, however, is a back port of functionality found in Python 3's standard library, and is only intended to be used with Python versions <= 2.7.
This PR updates the `setup.py` file to only include the `futures` package in the `python-lambda` install only when Python 2 is being used.
This closes issue #59

Selectively install futures package based on Python version

---

aws_lambda/aws_lambda.py

While using `lambda deploy` I was getting error:
```python
(getreportdata)aameer@falcon:~/Documents/projects/getreportdata$ lambda deploy
Gathering pip packages
Installing boto3==1.4.4
Installing botocore==1.5.62
Installing certifi==2017.11.5
Installing chardet==3.0.4
Installing click==6.6
Installing docutils==0.12
Installing futures==3.0.5
Installing idna==2.6
Installing jmespath==0.9.0
Installing pyaml==15.8.2
Installing python-dateutil==2.5.3
Installing PyYAML==3.11
Installing requests==2.18.4
Installing s3transfer==0.1.11
Installing six==1.10.0
Installing urllib3==1.22
Bundling: 'event.json'
Bundling: 'service.pyc'
Bundling: 'service.py'
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
Updating your Lambda function
Starting new HTTPS connection (1): …
```

adding region to `get_account_id` avoid failures

---

aws_lambda/aws_lambda.py

If an environment variable is added to the config, which is just a number, it is decoded from YAML into an int which causes a botocore.exceptions.ParamValidationError
Here is the relevant part of the stack trace:
botocore/validate.py", line 291, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Environment.Variables.lowThreshold, value: 5, type: <class 'int'>, valid types: <class 'str'>
When I changed the relevant code, casting `get_environment_variable_value(value)` to type `str`, it  succeeded in uploading the intended environment variable to AWS without errors.

Strong cast environment variables to type string

---

aws_lambda/aws_lambda.py

Changed parameter name `requirements` to `use_requirements` in function `deploy_s3` so it corresponds with the named argument gived in `scripts/lambda` line 116

Corrected 'deploy_s3' argument name

---

aws_lambda/aws_lambda.py

When using `deploy_s3`, the `update_function` and `create_function` functions take `use_s3` as `*args` and `s3_file` as `**kwargs`, which causes the `s3_file` to be empty and `use_s3` to equal `(True, <s3_file>)`, which then causes the deployment to fail because the `S3Key` value submitted to AWS is just `{}`.
This PR fixes it so that those arguments are properly passed and deployment goes through.

Fix for handling S3 deployment arguments

---

aws_lambda/aws_lambda.py
aws_lambda/project_templates/config.yaml

This might need a little more polish, but I added the ability to set/update tags on a function.
The behavior for a new function is straightforward because `create_function` accepts a `Tags` keyword.
For `update_function_configuration` it's a little trickier since that does not accept `Tags`.  The implementation I chose is to only update the existing tags if `tags` is set in the config.  If so, all existing tags are wiped and the supplied ones are applied.  If `tags` is not set in the config then the tags are left alone.
Update - on further thought perhaps tags should be applied on an update, but existing ones should be left alone.  Thoughts?

Add the ability to set tags on a function

---

aws_lambda/aws_lambda.py
scripts/lambda

Fixes #86 (@karthich)
** Breaks backwards compatibility! **
I changed the `--use-requirements` flag to `--requirements <PATH>` to allow a path to be specified.
If you are concerned about backwards compatibility the existing flag and behavior can be preserved.  I think it might be confusing to have two flags that do roughly the same thing, but I'm not sure how many people are using the current behavior.

Change --use-requirements to --requirements <PATH> (#86)

---

aws_lambda/aws_lambda.py

The VPC settings are applied on updates, but they were missing on creation.  Added them in.  #101

Set the VPC during lambda creation time (#101)

---

requirements.txt
setup.py

For some odd reason futures is being installed despite running python3. This is a quick fix tested on both python 3.6.3 and 2.7 to ensure futures is only installed on version 2.
Issue #106

Fixed installation of futures on python3

---

aws_lambda/aws_lambda.py
scripts/lambda

This adds a command line option called `--preserve-vpc` which allows you to omit the VPC settings (i.e. subnets and security groups) so that it will preserve whatever settings are already present on updates. This is useful when deploying the same function to multiple accounts where the security groups and subnets will necessarily change.

added cli option to preserve VPC settings on update; fixes #78

---

.gitignore
README.rst
aws_lambda/__init__.py
aws_lambda/aws_lambda.py
aws_lambda/helpers.py
setup.cfg
setup.py
tests/unit/test_LambdaContext.py

I could have done this differently but this was easiest for me as I already had my own fork. I took the changes from @simon-weber to abstractly declare install_requires (which was in its own separate PR) and the changes from @kmbenitez to use subprocess instead of pip internals (which was not in a PR). The first is a harmless change that was being asked for; the second is a necessary change to fix a bug that prevents more than one package from being deployed (which has existed since 3.2.2 - ever since pip changed its internals, apparently).

combined changes from simon-weber and kmbenitez; will fix #126

---

.gitignore
aws_lambda/aws_lambda.py
aws_lambda/project_templates/config.yaml

This fixes the problem we introduced in the last version that prevents deploying without a requirements.txt file (see #128); also adds regions as requested in #104, and support for concurrency as requested in #103.

fixes for #128 and #104 and #103

---

aws_lambda/aws_lambda.py

Copy the permissions and stats to the zip files so that executable binary files remain executable.

Copy stat of the files into the zip files

---

.travis.yml
aws_lambda/aws_lambda.py
tests/dev_requirements.txt
tests/unit/test_LambdaContext.py
tests/unit/test_readHelper.py

This silences the PyYAML `load` warning on invocation. The warning (and options for silencing/correcting it) is described here: [PyYAML yaml.load](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).
Implementing `full_load` still allows for the full set of yaml syntax.
Additionally this adds a new test case for the `read` helper that uses the loader and a minor fix the the other a failing unit test.

PyYAML loader fix

---

.travis.yml

AWS only supports python 3.6 and 3.7.
Also, python 3.3 reached the end of its life on 29 September 2017.

Remove python3.3 from Travis

---

.travis.yml
Pipfile
Pipfile.lock
README.md

Tests were failing for the latest commit in Python versions 3.5, 3.6 and 3.7. This PR fixes this by:
* removing testing for Python 3.5 since that runtime is not supported in [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python.html)
* updating the Pipfile to unpin Python 3.8 as the only allowed Python version.

Tests passing for all Python versions >= 3.6

---

setup.py

python-lambda is not getting installed correctly when using pip ( #485 ). This is being fixed by adding back `install_requires` with a list of requirements in `setup.py`.

Adding back the required packages to setup.py for successful installation

---

.travis.yml

With CI failures such as the ones in #531, my suspicion is that it is due to older pip versions on Travis systems. Planning to upgrade `pip` before installing other packages.

Testing out a change with Travis config to stop Python3.6 CI failures

---

Pipfile
Pipfile.lock
setup.py

The older version of `boto3` that has been pinned for this library needs to be updated, so `python-lambda` can work successfully with other codebases (see #500). This PR loosens the range of `boto3` that is allowed. In a future version, the minimum version will be increased as well.

Allowing more up-to-date boto3 versions

---

aws_lambda/aws_lambda.py
setup.py

This PR fixes issue https://github.com/nficano/python-lambda/issues/711 by adding a waiter on `function_updated`.

fix lambda deployment
